### ISSUE TITLE
Plane layout

### ISSUE THREAD

**Issue by NVessel** [renatav/GraphDrawing#17]
Hello! I would like to ask some question about grad. Does this library contain layout algorithm / layout which builds plane layout for planar graphs? I've heard it might be done with Tutte straight-line drawing

**Comment by graph-algorithms-admin** [comment]
@NVessel You can also get planar graph drawings from https://github.com/graph-algorithms/edge-addition-planarity-suite

**Comment by NVessel** [comment]
> 
> 
> @NVessel You can also get planar graph drawings from https://github.com/graph-algorithms/edge-addition-planarity-suite

Yeah, thanks, but edge-addition-planarity-suite is too hard for me plus it's written on pure C. So can I use Tutte straight-line drawing or not?

**Comment by graph-algorithms-admin** [comment]
@NVessel The edge-addition-planarity-suite includes a [downloadable exe file](https://github.com/graph-algorithms/edge-addition-planarity-suite/releases/tag/Version_3.0.1.0), so you don't even have to play with compiling C if you don't want to. The front page also gives detailed developer environment setup instructions that can be followed to build the code for yourself without even really needing to know C. Above, you asked for a library that contains a "layout algorithm /layout which builds a plane layout for planar graphs." Using the exe file, you can create a straight line visibility representation of a planar graph as well as an ASCII art rendition of the straight line visibility representation of planar graphs. The Graph Drawing Conference paper describing the algorithm is also the second bullet point link on the front page of https://github.com/graph-algorithms/edge-addition-planarity-suite. I encourage you to check out the exe program as it may do what you need.

**Comment by renatav** [comment]
@NVessel  You can use Tutte straight line drawing to lay out simple graphs. If you need to handle graphs with hundreds of nodes, it's better to look into more complex algorithms. When I did my research, a couple of years ago, there weren't any good open source implementations of planar drawing algorithms which I could integrated into my Java applications. Things might have changed though.

**Comment by NVessel** [comment]
Thanks all for answers, but I  planned to include drawing algorithm to my Java app too. Perhaps, I could use Tutte for small graphs at least. Thanks again.
